name: Release
on: { release: { types: [published] } }
jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
        env: { ELECTRON_MIRROR: "https://npmmirror.com/mirrors/electron/", npm_config_registry: "https://registry.npmmirror.com" }