name: Release Build
on:
  push:
    tags: [v*]
permissions:
  contents: write

jobs:
  build:
    name: Build Installers
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install dependencies
        run: npm install
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          npm_config_registry: https://registry.npmmirror.com

      - name: Build source
        run: npm run build
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          npm_config_registry: https://registry.npmmirror.com

      - name: Package installer
        run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Melodix-${{ matrix.os }}
          path: release/